/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.vendas;

public class CadastroVendas extends javax.swing.JFrame {

    /**
     * Creates new form vendas
     */
    public CadastroVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextTotal = new javax.swing.JTextField();
        jTextId = new javax.swing.JTextField();
        jTextIdCliente = new javax.swing.JTextField();
        jTextIdProduto = new javax.swing.JTextField();
        jTextValorUnitario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSair = new javax.swing.JButton();
        jButtonInserir = new javax.swing.JButton();
        jButtonAterar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jLabel1.setText("Total");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 150, 50, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Cadastro de Vendas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 10, 200, 22);

        jLabel3.setText("Id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 50, 14);

        jLabel4.setText("Id Cliente");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 80, 50, 14);

        jLabel5.setText("Id Produto");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 80, 70, 14);

        jLabel6.setText("Valor Unitário");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 150, 90, 14);

        jTextTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTotalActionPerformed(evt);
            }
        });
        getContentPane().add(jTextTotal);
        jTextTotal.setBounds(190, 170, 60, 20);
        getContentPane().add(jTextId);
        jTextId.setBounds(20, 100, 70, 20);
        getContentPane().add(jTextIdCliente);
        jTextIdCliente.setBounds(149, 100, 80, 20);
        getContentPane().add(jTextIdProduto);
        jTextIdProduto.setBounds(289, 100, 70, 20);
        getContentPane().add(jTextValorUnitario);
        jTextValorUnitario.setBounds(20, 170, 60, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Id Cliente", "Id Produto", "Valor Unitário", "Valor Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 630, 150);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(470, 130, 80, 30);

        jButtonInserir.setText("Inserir");
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInserir);
        jButtonInserir.setBounds(470, 40, 80, 30);

        jButtonAterar.setText("Alterar");
        getContentPane().add(jButtonAterar);
        jButtonAterar.setBounds(470, 70, 80, 30);

        jButtonDeletar.setText("Deletar");
        getContentPane().add(jButtonDeletar);
        jButtonDeletar.setBounds(470, 100, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTotalActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        String id_cliente = jTextIdCliente.getText();
        String id_produto = jTextIdProduto.getText();
        String valor_unitario = jTextValorUnitario.getText();
        String total = jTextTotal.getText();
        vendas v = new vendas();
        v.setId_cliente(WIDTH);
        v.setId_produto(WIDTH);
        v.setValor_unitario(TOP_ALIGNMENT);
        v.setTotal(TOP_ALIGNMENT);
        
    }//GEN-LAST:event_jButtonInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAterar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextIdCliente;
    private javax.swing.JTextField jTextIdProduto;
    private javax.swing.JTextField jTextTotal;
    private javax.swing.JTextField jTextValorUnitario;
    // End of variables declaration//GEN-END:variables
}
