/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.produtos;

public class CadastroProdutos extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextIdFornecedor = new javax.swing.JTextField();
        jTextId = new javax.swing.JTextField();
        jTextDescricao = new javax.swing.JTextField();
        jTextEstoque = new javax.swing.JTextField();
        jTextPrecoUnitario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSair = new javax.swing.JButton();
        jButtonInserir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jLabel1.setText("Id Fornecedor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 200, 80, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Cadastro de Produtos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 20, 210, 22);

        jLabel3.setText("Id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 60, 14);

        jLabel4.setText("Descrição");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 80, 60, 14);

        jLabel5.setText("Estoque");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 60, 14);

        jLabel6.setText("Preço Unitário");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 140, 80, 14);

        jTextIdFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextIdFornecedor);
        jTextIdFornecedor.setBounds(20, 220, 310, 20);
        getContentPane().add(jTextId);
        jTextId.setBounds(20, 100, 70, 20);

        jTextDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescricaoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextDescricao);
        jTextDescricao.setBounds(180, 100, 230, 20);

        jTextEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(jTextEstoque);
        jTextEstoque.setBounds(20, 160, 80, 20);

        jTextPrecoUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrecoUnitarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextPrecoUnitario);
        jTextPrecoUnitario.setBounds(180, 160, 90, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descrição", "Estoque", "Preço Unitário", "Id Fornecedor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 260, 550, 150);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(490, 130, 80, 30);

        jButtonInserir.setText("Inserir");
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInserir);
        jButtonInserir.setBounds(490, 40, 80, 30);

        jButtonAlterar.setText("Alterar");
        getContentPane().add(jButtonAlterar);
        jButtonAlterar.setBounds(490, 70, 80, 30);

        jButtonDeletar.setText("Deletar");
        getContentPane().add(jButtonDeletar);
        jButtonDeletar.setBounds(490, 100, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextIdFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdFornecedorActionPerformed

    private void jTextDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescricaoActionPerformed

    private void jTextEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEstoqueActionPerformed

    private void jTextPrecoUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrecoUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPrecoUnitarioActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        String estoque = jTextEstoque.getText();
        String id_fornecedor = jTextIdFornecedor.getText();
        String descricao = jTextDescricao.getText();
        String preco_unitario = jTextPrecoUnitario.getText();
        produtos p = new produtos();
        p.setEstoque(ERROR);
        p.setId_fornecedor(HIDE_ON_CLOSE);
        p.setDescricao(descricao);
        p.setPreco_unitario(LEFT_ALIGNMENT);
    }//GEN-LAST:event_jButtonInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextDescricao;
    private javax.swing.JTextField jTextEstoque;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextIdFornecedor;
    private javax.swing.JTextField jTextPrecoUnitario;
    // End of variables declaration//GEN-END:variables
}
